swagger: '2.0'
info:
  title: dimple
  description: |
    dimple api
  version: "0.1.0"
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  reCaptcha:
    type: oauth2
    authorizationUrl: http://6120.eu/dimple/
    flow: implicit
    scopes:
      write:send: send
paths:
  /send:
    get:
      summary: send some crypto
      operationId: send
      description: send some crypto
      security:
        - reCaptcha: []
      responses:
        200:
          description: return txid
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: to
          in: query
          type: string
          required: true
  /list:
    get:
      summary: list past sent crypto
      operationId: list
      description: return past sent crypto
      responses:
        200:
          description: Crypto sent
          schema:
            type: array
            items:
              $ref: '#/definitions/list_item'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  list_item:
    type: object
    properties:
      addr:
        type: string
        description: Some string
      txid:
        type: string
        description: txid
      amount:
        type: string
        description: amount sent
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
