// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Listing listing
// swagger:model listing

type Listing struct {

	// Some string
	Addr string `json:"addr,omitempty"`

	// amount sent
	Amount int64 `json:"amount,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`
}

/* polymorph listing addr false */

/* polymorph listing amount false */

/* polymorph listing txid false */

// Validate validates this listing
func (m *Listing) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Listing) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Listing) UnmarshalBinary(b []byte) error {
	var res Listing
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
